---
title: "Qui suis-je ?"
output: html_document
---

<div class="service">

### En résumé

Ingénieur et docteur en agronomie, la science des données occupe une place centrale dans toutes mes expériences (formation, premiers emplois, thèse, expériences associatives et personnelles). J'aime apprendre et partager mes compétences. Je suis fier d'appartenir à la communauté d'utilisateur du logiciel <a href="https://www.r-project.org/"><i class="fab fa-r-project"></i></a>. J'exerce aujourd'hui mon activité en tant qu'indépendant pour vous accompagner au cours de vos expéditions dans le monde de la donnée.
                    
À titre personnel, je suis également un grimpeur passionné. En plus de grimper régulièrement, j'ai passé le diplôme fédéral d'initiateur en structure artificielle afin de partager cette passion à un public jeune ou adulte. Il est possible que vous en entendiez parler d'escalade sur mon blog ! 

<a href="/doc/CV_BenjaminLouis.pdf" class="btn btn-primary btn-lg">Télécharger mon CV</a>

### Compétences

+ DataScience : collecte, visualisation et exploration de données, analyses statistiques, modélisation

+ Logiciel <i class="fab fa-r-project"></i>, RStudio, RShiny, Création de package, OpenBUGS

+ LaTeX, (R)Markdown, HTML, CSS

+ Modélisation de la dynamique de la matière organique du sol, microbiologie des sols

+ Initiateur sur structure artificielle d'escalade

### Expériences professionnelles

#### Chercheur et datascientist

<div class="table">

|           |                                                                                           |
|:----------|:------------------------------------------------------------------------------------------|
|Depuis 2017|Consultant-Formateur en science des données - Freelance|
|2013 - 2016|Doctorant en agronomie et biologie - UMR SAS, INRA, Rennes|
|2013 - 2016|Ingénieur de recherche - Couplage de base de données, Optimisation d'échantillonnage spatiale - UMR SAS, INRA, Rennes|
|2013 - 2016|Ingénieur de recherche - Optimisatoin d'échantillonnage spatiale, Impact d'incertitudes de mesure - US Infosol, INRA, Orléans|

</div>

#### Formateur et enseignant

|           |                                                                                           |
|:----------|:------------------------------------------------------------------------------------------|
|Depuis 2017|Diverses formations en datascience|
|2013 - 2015|Enseignement en datascience et agronomie (128h) aux élèves ingénieurs : cours, TD, rapporteur de mémoires, jury de soutenance, projet professionnalisant.|
|2011 - 2016|Formations ponctuelles en statistiques pour des collègues de travai|

### Formation

|           |                                                                                           |
|:----------|:------------------------------------------------------------------------------------------|
|2013 - 2016|Doctorat - Agrocampus Ouest, Rennes|
|           |Prise en compte du rôle de la diversité microbienne dans la simulation de la dynamique de la matière organique du sol (MOS) dans un contexte de transition agro-écologique|
|2007 - 2010|Ingénieur agronome - Agrocampus Ouest, Rennes|
|           |Spécialité : statistiques appliquées (master)|

### Contributions scientifiques

#### Thèse

Louis, B. (2016). <a href="https://tel.archives-ouvertes.fr/tel-01538388/">Prise en compte du rôle de la diversité microbienne dans la simulation de la dynamique de la matière organique du sol (MOS) dans un contexte de transition vers l'agro-écologie</a> (Doctoral dissertation, Agrocampus Ouest).

#### Publications

##### 2017

Saby, N. P. A., Swiderski, C., Lemercier, B., Walter, C., Louis, B. P., Eveillard, P., & Arrouays, D. (2017). Is pH increasing in the noncalcareous topsoils of France under agricultural management? A statistical framework to overcome the limitations of a soil test database. Soil Use and Management, 33(3), 460-470. <a href="https://doi.org/10.1111/sum.12369">doi:10.1111/sum.12369</a>

Matos‐Moreira, M., Lemercier, B., Dupas, R., Michot, D., Viaud, V., Akkal‐Corfini, N.,Louis, B P.,. & Gascuel‐Odoux, C. (2017). High‐resolution mapping of soil phosphorus concentration in agricultural landscapes with readily available or detailed survey data. European Journal of Soil Science, 68(3), 281-294. <a href="https://doi.org/10.1111/ejss.12420">doi:10.1111/ejss.12420</a>

##### 2016 

Louis, B. P., Maron, P. A., Menasseri-Aubry, S., Sarr, A., Lévêque, J., Mathieu, O., Jolivet, C., Leterme, P., & Viaud, V. (2016). Microbial diversity indexes can explain soil carbon dynamics as a function of carbon source. PloS one, 11(8).  <a href="https://doi.org/10.1371/journal.pone.0161251">doi:10.1371/journal.pone.0161251</a>.

Louis, B. P., Maron, P. A., Viaud, V., Leterme, P., & Menasseri-Aubry, S. (2016). Soil C and N models that integrate microbial diversity. Environmental chemistry letters, 14(3), 331-344. <a href="https://doi.org/10.1007/s10311-016-0571-5">doi:10.1007/s10311-016-0571-5</a>

##### 2014 

Paroissien, J. B., Saby, N. P. A., de Forges, A. R., Arrouays, D., & Louis, B. (2014). Populating soil maps with legacy data from a soil testing databases. GlobalSoilMap: Basis of the global spatial soil information system, 319. <a href="https://doi.org/10.1201/b16500-59">doi:10.1201/b16500-59</a>

Arrouays, D., Marchant, B. P., Saby, N. P., Meersmans, J., Jolivet, C., Orton, T. G., Martin, M. P., Bellamy, P. H., Lark, R. M., Louis, B. P., Allard, D., & Kibblewhite, M. (2014). On soil carbon monitoring networks. In Soil Carbon (pp. 59-68). Springer, Cham. <a href="https://doi.org/10.1007/978-3-319-04084-4_6">doi:10.1007/978-3-319-04084-4_6</a>

Louis, B. P., Saby, N. P. A., Orton, T. G., Lacarce, E., Boulonne, L., Jolivet, C., Ratie C. & Arrouays, D., (2014). Statistical sampling design impact on predictive quality of harmonization functions between soil monitoring networks. Geoderma, 213, 133-143. <a href="https://doi.org/10.1016/j.geoderma.2013.07.018">doi:10.1016/j.geoderma.2013.07.018</a>

Saby, N. P. A., Lemercier, B., Arrouays, D., Leménager, S., Louis, B. P., Millet, F., Paroissien, J-B., Schellenberger, E., Squividant, H., Swiderski, C., Toutain, B., Walter, C. & Bardy, M. (2014). Le programme Base de Données des Analyses de Terre (BDAT): Bilan de 20 ans de collecte de résultats d’analyses. Etude et Gestion des Sols (21), 141-150. <a href="https://epic.awi.de/35367/2/Saby_EGS_21_1_2111_141_150_web.pdf">Full text</a>

##### 2012

Meersmans, J., Martin, M. P., De Ridder, F., Lacarce, E., Wetterlind, J., De Baets, S., Le Bas, C., Louis, B. P., Orton, T. G., Bispo, A., & Arrouays, D. (2012). A novel soil organic C model using climate, soil type and management data at the national scale in France. Agronomy for sustainable development, 32(4), 873-888. <a href="https://doi.org/10.1007/s13593-012-0085-x">doi:10.1007/s13593-012-0085-x</a>

</div>

