baseurl = "/"
#baseurl = "https://www.benjaminlouis-stat.fr/"
#baseurl = "https://benjaminlouis-stat.netlify.com/"
title = "Benjamin Louis | Data Scientist - Expertise R - Consultance et Formation"
theme = "hugo-universal-theme"
languageCode = "en-us"
# Site language. Available translations in the theme's `/i18n` directory.
defaultContentLanguage = "fr"
# Enable comments by entering your Disqus shortname
disqusShortname = "benlo-stat"
# Enable Google Analytics by entering your tracking code
googleAnalytics = ""#"UA-117750022-1"
# Ignoring
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]
# For good rendering in local
relativeURLs = true

# Define the number of posts per page
paginate = 10


[languages]
  [languages.fr]
    weight = 1
    languageName = "fr"
  [languages.en]
    weight = 2
    languageName = "en"



[menu]

# Main menu

[[menu.main]]
    name = "Home"
    url  = "/"
    weight = 1
    
[[menu.main]]
    name = "Qui suis-je ?"
    url  = "/apropos/"
    weight = 2

[[menu.main]]
    name = "Blog"
    url  = "/blog/"
    weight = 3

[[menu.main]]
    name = "Contact"
    url  = "/contact/"
    weight = 4

# Top bar social links menu

[[menu.topbar]]
    weight = 1
    name = "GitHub"
    url = "https://github.com/BenjaminLouis"
    pre = "<i class='fab fa-2x fa-github'></i>"

[[menu.topbar]]
    weight = 2
    name = "Twitter"
    url = "http://twitter.com/benlo_7"
    pre = "<i class='fab fa-2x fa-twitter'></i>"

[[menu.topbar]]
    weight = 3
    name = "ResearchGate"
    url = "https://www.researchgate.net/profile/Benjamin_Louis"
    pre = "<i class='fab fa-2x fa-researchgate'></i>"

[[menu.topbar]]
    weight = 4
    name = "LinkedIn"
    url = "https://www.linkedin.com/in/benjamin-louis-04611a90/"
    pre = "<i class='fab fa-2x fa-linkedin-in'></i>"

[[menu.topbar]]
    weight = 5
    name = "Email"
    url = "mailto:contact@benjaminlouis-stat.fr"
    pre = "<i class='fa fa-2x fa-envelope'></i>"

[params]
    viewMorePostLink = "/blog/"
    author = "Benjamin"
    defaultKeywords = ["statistics", "R", "shiny", "CSS", "HTML", "versus", "Point_of_View"]
    defaultDescription = "Site template made by devcows using hugo"
    mainSections = ["blog"]

    # Google Maps API key (if not set will default to not passing a key.)
    googleMapsApiKey = ""#"AIzaSyCFhtWLJcE30xOAjcbSFi-0fnoVmQZPb1Y"
    googleAnalytics = ""#"UA-117750022-1" # Ajout perso pour intégrer dans head

    # Style options: default (light-blue), blue, green, marsala, pink, red, turquoise, violet
    style = "green"

    # Since this template is static, the contact form uses www.formspree.io as a
    # proxy. The form makes a POST request to their servers to send the actual
    # email. Visitors can send up to a 1000 emails each month for free.
    #
    # What you need to do for the setup?
    #
    # - set your email address under 'email' below
    # - upload the generated site to your server
    # - send a dummy email yourself to confirm your account
    # - click the confirm link in the email from www.formspree.io
    # - you're done. Happy mailing!
    #
    # Enable the contact form by entering your Formspree.io email
    email = "contact@benjaminlouis-stat.fr"

    #about_us = ""
    copyright = "&copy; 2018 - 2019, Benjamin Louis - <a href = \"ml/index.html\"> Mentions légales </a> "

    # Format dates with Go's time formatting
    date_format = "2 Jan 2006"

    logo = "img/pastille.png"
    logo_small = "img/pastille-small.png"
    address = """<p><strong>+33(0)6 47 94 72 38</strong>
        <br>contact@benjaminlouis-stat.fr
        <br>
        <strong>France</strong>
      </p>
      """
    #latitude = ""
    #longitude = ""

[Permalinks]
    blog = "/blog/:filename/"  #"/blog/:year/:month/:day/:filename/"

# Enable or disable top bar with social icons
[params.topbar]
    enable = true
    text = ""#"""<p class="hidden-sm hidden-xs">Contact us on +420 777 555 333 or hello@universal.com.</p>
      #<p class="hidden-md hidden-lg"><a href="#" data-animate-hover="pulse"><i class="fa fa-phone"></i></a>
      #<a href="#" data-animate-hover="pulse"><i class="fa fa-envelope"></i></a>
      #</p>
      #"""

# Enable and disable widgets for the right sidebar
[params.widgets]
    categories = true
    tags = true
    search = true

[params.carousel]
    enable = true
    # All carousel items are defined in their own files. You can find example items
    # at 'exampleSite/data/carousel'.
    # For more informtion take a look at the README.

[params.features]
    enable = true
    # All features are defined in their own files. You can find example items
    # at 'exampleSite/data/features'.
    # For more informtion take a look at the README.

[params.testimonials]
    enable = false
    # All testimonials are defined in their own files. You can find example items
    # at 'exampleSite/data/testimonials'.
    # For more informtion take a look at the README.
    title = "Testimonials"
    subtitle = "We have worked with many clients and we always like to hear they come out from the cooperation happy and satisfied. Have a look what our clients said about us."

[params.see_more]
    enable = true
    icon = "fa fa-file-code-o"
    title = "Qui suis-je ?"
    subtitle = "<p> Ingénieur et docteur en agronomie, la science des données occupe une place centrale dans toutes mes expériences (formation, premiers emplois, thèse, expériences associatives et personnelles). J'aime apprendre et partager mes compétences. Je suis fier d'appartenir à la communauté d'utilisateur du logiciel <a href='https://www.r-project.org/'><i class='fab fa-r-project'></i></a>. J'exerce aujourd'hui mon activité en tant qu'indépendant pour vous accompagner au cours de vos expéditions dans le monde de la donnée. </p> <p>À titre personnel, je suis également un grimpeur passionné. En plus de grimper régulièrement, j'ai passé le diplôme fédéral d'initiateur en structure artificielle afin de partager cette passion à un public jeune ou adulte. Il est possible que vous entendiez parler d'escalade sur mon blog !</p>"
    link_url = "/doc/CV_BenjaminLouis.pdf"
    link_text = "Télécharger mon CV"

[params.clients]
    enable = true
    # All clients are defined in their own files. You can find example items
    # at 'exampleSite/data/clients'.
    # For more informtion take a look at the README.
    title = "On a travaillé ensemble"
    subtitle = ""

[params.recent_posts]
    enable = true
    title = "Sur mon blog"
    subtitle = ""
